export const CONCEPTS = [
  "Victorian architecture", "acid trip", "underwater cathedral", "1970s space station", 
  "jungle temple", "neon noir", "rural Japanese countryside", "cyberpunk market", 
  "art deco lounge", "brutalist concrete", "gothic cathedral", "post-apocalyptic wasteland", 
  "holographic concert", "steampunk laboratory", "abandoned mall", "crystal cavern", 
  "ancient library", "floating island", "alien flora", "bioluminescent swamp", 
  "retro diner", "samurai dojo", "clockwork city", "glitch art", "hyper-pop dreamscape", 
  "monochrome desert", "solarpunk metropolis", "medieval tournament", "haunted forest", 
  "jazz club", "neon signs", "viking longship", "subterranean bunker", "zen garden", 
  "noir detective office", "cybernetic implants", "shatter glass", "melted wax", 
  "geometric shapes", "liquid metal", "smoke trails", "vintage polaroid", "double exposure", 
  "fractal geometry", "optical illusion", "surrealism", "low poly", "voxel art"
];

export const OPPOSITES: Record<string, string> = {
  bright: "dark", dark: "bright", fast: "slow", slow: "fast",
  minimal: "maximal", maximal: "minimal", calm: "chaotic", chaotic: "calm",
  realistic: "abstract", abstract: "realistic", warm: "cool", cool: "warm",
  smooth: "gritty", gritty: "smooth", futuristic: "vintage", vintage: "futuristic",
  clean: "dirty", dirty: "clean", loud: "quiet", quiet: "loud",
  sharp: "blurry", blurry: "sharp", day: "night", night: "day",
  happy: "sad", sad: "happy", colorful: "monochrome", monochrome: "colorful",
  complex: "simple", simple: "complex", natural: "artificial", artificial: "natural",
  dry: "wet", wet: "dry", heavy: "light", light: "heavy", open: "closed", closed: "open",
  new: "old", old: "new", wide: "narrow", narrow: "wide", matte: "glossy", glossy: "matte"
};

export const MOOD_BOARDS = [
  { name: "Cinematic", desc: "Dramatic lighting, film grain, wide aspect.", background: "linear-gradient(135deg, #0a1628, #1a0a2e)", icon: "🎬", style: "cinematic film still, 35mm photograph", mood: "dramatic", colorPalette: "teal and orange", lighting: "volumetric god rays" },
  { name: "Lo-fi", desc: "Nostalgic, dusty, vintage analog feel.", background: "linear-gradient(135deg, #1a0f05, #0a1a14)", icon: "📼", style: "lo-fi aesthetic, VHS artifact", mood: "nostalgic", colorPalette: "muted pastels", lighting: "soft diffuse" },
  { name: "Vaporwave", desc: "80s retro-futurism, neon pinks & cyans.", background: "linear-gradient(135deg, #2b00ff, #ff00c8)", icon: "🌴", style: "vaporwave aesthetic, synthwave", mood: "dreamy", colorPalette: "neon cyan, magenta", lighting: "neon glow" },
  { name: "Brutalist", desc: "Raw concrete, heavy geometry, minimal.", background: "linear-gradient(135deg, #444, #222)", icon: "🏢", style: "brutalist architecture, raw concrete", mood: "oppressive", colorPalette: "monochrome grays", lighting: "harsh sunlight" },
  { name: "Organic/Nature", desc: "Lush greenery, natural light, peaceful.", background: "linear-gradient(135deg, #0f380f, #8bac0f)", icon: "🌿", style: "national geographic photography, lush foliage", mood: "peaceful", colorPalette: "earth tones, forest greens", lighting: "golden hour" },
  { name: "Neon Noir", desc: "Cyberpunk, rain-slicked streets, moody.", background: "linear-gradient(135deg, #001133, #00e5ff)", icon: "🌃", style: "cyberpunk 2077 aesthetic, blade runner style", mood: "mysterious", colorPalette: "neon blue, deep blacks", lighting: "neon light sources, wet reflections" },
  { name: "Minimal", desc: "Clean lines, negative space, simple.", background: "linear-gradient(135deg, #eee, #fff)", icon: "⚪", style: "minimalist design, clean background", mood: "calm", colorPalette: "pure white, soft cream", lighting: "even studio lighting" },
  { name: "Maximal", desc: "Overwhelming detail, chaotic, vibrant.", background: "linear-gradient(135deg, #ff0000, #ffff00)", icon: "🎆", style: "maximalist, hyper-detailed", mood: "chaotic", colorPalette: "vibrant rainbow colors", lighting: "flashy" },
  { name: "Retro/Vintage", desc: "Faded photos, 70s aesthetics, warm.", background: "linear-gradient(135deg, #d4a373, #faedcd)", icon: "📻", style: "1970s vintage photograph, kodachrome", mood: "nostalgic", colorPalette: "sepia, faded orange", lighting: "warm golden hour" },
  { name: "Futuristic", desc: "Sleek chrome, holograms, high-tech.", background: "linear-gradient(135deg, #000, #333)", icon: "🚀", style: "sci-fi futuristic, clean tech", mood: "clinical", colorPalette: "chrome, glowing blue", lighting: "clinical white fluorescence" },
  { name: "Dreamy/Ethereal", desc: "Soft focus, clouds, magical.", background: "linear-gradient(135deg, #e0c3fc, #8ec5fc)", icon: "☁️", style: "ethereal dreamscape, soft magical", mood: "dreamy", colorPalette: "soft pastel purples", lighting: "glowing aura" },
  { name: "Gritty/Industrial", desc: "Rust, dirt, heavy machinery.", background: "linear-gradient(135deg, #594f4f, #544a48)", icon: "⚙️", style: "industrial grit, rusted metal", mood: "gritty", colorPalette: "rust orange, oily blacks", lighting: "flickering fluorescent" },
  { name: "Pastel/Kawaii", desc: "Cute, soft colors, playful.", background: "linear-gradient(135deg, #ff9a9e, #fecfef)", icon: "🌸", style: "kawaii aesthetic, soft cute", mood: "happy", colorPalette: "bubblegum pink, mint", lighting: "bright airy daylight" },
  { name: "Dark Academia", desc: "Old books, mahogany, moody scholars.", background: "linear-gradient(135deg, #3e2723, #1b0000)", icon: "📚", style: "dark academia, vintage library", mood: "melancholy", colorPalette: "mahogany, forest green", lighting: "dim candlelight" },
  { name: "Abstract", desc: "Shapes, forms, non-representational.", background: "linear-gradient(135deg, #ff0844, #ffb199)", icon: "🎨", style: "abstract expressionism", mood: "surreal", colorPalette: "bold primaries", lighting: "experimental lighting" },
  { name: "Photorealistic", desc: "Looks like a real photograph.", background: "linear-gradient(135deg, #ece9e6, #ffffff)", icon: "📷", style: "ultra photorealistic, 8k resolution", mood: "neutral", colorPalette: "natural colors", lighting: "realistic shadows" }
];

export const NEGATIVE_PROMPTS = [
  "blurry", "extra fingers", "watermark", "low quality", "oversaturated", "deformed", 
  "text artifacts", "noise", "bad anatomy", "cropped", "out of frame", "duplicate", 
  "morbid", "mutilated", "poorly drawn", "bad proportions", "gross proportions", 
  "missing arms", "missing legs", "extra arms", "extra legs", "fused fingers", 
  "too many fingers", "long neck"
];

export const NEGATIVE_PRESETS: Record<string, string[]> = {
  "Clean Portrait": ["deformed", "bad anatomy", "poorly drawn", "extra fingers", "blurry", "watermark", "text"],
  "Photorealistic": ["illustration", "painting", "cartoon", "anime", "3d render", "low quality", "noise", "oversaturated"],
  "Anime": ["photorealistic", "3d render", "realistic human", "blurry", "noise", "deformed", "bad proportions"],
  "Abstract Art": ["realistic", "human figure", "text", "watermark", "signature", "low resolution"],
  "Product Shot": ["messy background", "people", "hands", "blurry", "low quality", "distorted proportions", "text"],
};

export const COMMUNITY_PROMPTS = [
  { author: "@voidpainter", model: "SDXL", type: "image", difficulty: "intermediate", downloads: "2.4k", stars: "847", background: "linear-gradient(135deg, #0a1628, #1a0a2e)", prompt: "A sprawling cyberpunk metropolis under heavy rain, neon reflections in puddles, towering mega-corporation buildings, highly detailed architecture, cinematic lighting, 8k resolution, masterpiece, octane render.", mode: "image", fields: { subject: "A sprawling cyberpunk metropolis under heavy rain", mood: "mysterious", style: "cinematic lighting", resolution: "1024x1024" } },
  { author: "@synthwave_ai", model: "MusicGen", type: "music", difficulty: "beginner", downloads: "1.2k", stars: "450", background: "linear-gradient(135deg, #2b00ff, #ff00c8)", prompt: "1980s synthwave track, heavy analog synth bassline, driving gated snare drum, pulsing arpeggios, nostalgic retro-futuristic mood, 120 beats per minute.", mode: "music", fields: { subject: "1980s synthwave track", mood: "nostalgic", style: "120 beats per minute", resolution: "16:9" } },
  { author: "@facegen", model: "Flux", type: "image", difficulty: "advanced", downloads: "3.1k", stars: "920", background: "linear-gradient(135deg, #ece9e6, #ffffff)", prompt: "Extreme close-up macro photography of a human eye, incredibly detailed iris, reflection of a window in the pupil, skin pores visible, stray eyelashes, shallow depth of field, natural window lighting, shot on 100mm macro lens.", mode: "image", fields: { subject: "Extreme close-up macro photography of a human eye", mood: "neutral", style: "shallow depth of field", resolution: "1024x1024" } },
  { author: "@motionlab", model: "AnimateDiff", type: "video", difficulty: "advanced", downloads: "1.8k", stars: "623", background: "linear-gradient(135deg, #1a0f05, #0f1a0a)", prompt: "Camera panning slowly across a dusty, abandoned Victorian dining room, sunbeams illuminating floating dust motes through shattered stained glass windows, overgrown with creeping ivy, haunting atmosphere.", mode: "video", fields: { subject: "dusty, abandoned Victorian dining room", mood: "melancholy", style: "Camera panning slowly", resolution: "16:9" } },
  { author: "@pixelcraft", model: "SDXL", type: "image", difficulty: "beginner", downloads: "500", stars: "120", background: "linear-gradient(135deg, #ff9a9e, #fecfef)", prompt: "A vast field of giant glowing mushrooms, pastel color palette, soft dreamy lighting, studio ghibli style, whimsical atmosphere, 4k.", mode: "image", fields: { subject: "A vast field of giant glowing mushrooms", mood: "dreamy", style: "studio ghibli style", resolution: "1024x1024" } },
  { author: "@renderking", model: "SD 1.5", type: "image", difficulty: "intermediate", downloads: "300", stars: "85", background: "linear-gradient(135deg, #3e2723, #1b0000)", prompt: "Dark fantasy knight standing before an ancient stone gateway, glowing red runes, volumetric fog, dramatic chiaroscuro lighting, oil painting style.", mode: "image", fields: { subject: "Dark fantasy knight standing before an ancient stone gateway", mood: "dramatic", style: "oil painting style", resolution: "512x512" } },
  { author: "@videogen", model: "SVD", type: "video", difficulty: "intermediate", downloads: "900", stars: "410", background: "linear-gradient(135deg, #001133, #00e5ff)", prompt: "Drone flyover of a futuristic neon city at night, flying cars zooming past, rain hitting the camera lens, blade runner aesthetic, smooth motion.", mode: "video", fields: { subject: "Drone flyover of a futuristic neon city at night", mood: "mysterious", style: "blade runner aesthetic", resolution: "16:9" } },
  { author: "@beatmaker", model: "Stable Audio", type: "music", difficulty: "intermediate", downloads: "1.5k", stars: "600", background: "linear-gradient(135deg, #d4a373, #faedcd)", prompt: "Boom bap hip hop beat, 90bpm, dusty vinyl crackle sampled breakbeat, jazz piano chords, upright bass, chillhop vibe, lo-fi aesthetic.", mode: "music", fields: { subject: "Boom bap hip hop beat", mood: "chill", style: "dusty vinyl crackle sampled breakbeat", resolution: "1:1" } },
  { author: "@artdeco_ai", model: "Flux", type: "image", difficulty: "beginner", downloads: "400", stars: "150", background: "linear-gradient(135deg, #111, #333)", prompt: "A sleek 1930s art deco locomotive speeding through a snowstorm, polished chrome, glowing warm headlights, cinematic lighting, masterpiece illustration.", mode: "image", fields: { subject: "A sleek 1930s art deco locomotive speeding through a snowstorm", mood: "cinematic", style: "masterpiece illustration", resolution: "1024x1024" } },
  { author: "@characterforge", model: "SDXL", type: "image", difficulty: "advanced", downloads: "2.1k", stars: "780", background: "linear-gradient(135deg, #444, #222)", prompt: "Concept art character sheet of a space marine, multiple angles, neutral gray background, worn armor, precise line art, highly detailed, professional games industry standard.", mode: "image", fields: { subject: "Concept art character sheet of a space marine", mood: "clinical", style: "professional games industry standard", resolution: "1024x1024" } },
  { author: "@naturelens", model: "SDXL", type: "image", difficulty: "beginner", downloads: "850", stars: "320", background: "linear-gradient(135deg, #0f380f, #8bac0f)", prompt: "Close up portrait of a red fox in an autumn forest, golden hour lighting, sharp focus on the eyes, blurry background bokeh, National Geographic style.", mode: "image", fields: { subject: "Close up portrait of a red fox in an autumn forest", mood: "peaceful", style: "National Geographic style", resolution: "1024x1024" } },
  { author: "@synth_pop", model: "MusicGen", type: "music", difficulty: "beginner", downloads: "1.1k", stars: "430", background: "linear-gradient(135deg, #e0c3fc, #8ec5fc)", prompt: "Upbeat synth-pop track, 125 bpm, bright FM synthesizers, four-on-the-floor kick, catchy melodic hook, euphoric mood, festival anthem.", mode: "music", fields: { subject: "Upbeat synth-pop track", mood: "euphoric", style: "bright FM synthesizers", resolution: "16:9" } },
  { author: "@architect_ai", model: "Flux", type: "image", difficulty: "intermediate", downloads: "600", stars: "210", background: "linear-gradient(135deg, #eee, #fff)", prompt: "Minimalist modern living room interior, vast floor-to-ceiling windows overlooking a serene ocean, white curved furniture, sun-drenched, architectural digest style.", mode: "image", fields: { subject: "Minimalist modern living room interior", mood: "calm", style: "architectural digest style", resolution: "1024x1024" } },
  { author: "@vfx_guru", model: "AnimateDiff", type: "video", difficulty: "advanced", downloads: "2.5k", stars: "890", background: "linear-gradient(135deg, #ff0844, #ffb199)", prompt: "A glass statue shattering into thousands of pieces in extremely slow motion, fluid dynamics, particles flying toward the camera, black background, high contrast lighting.", mode: "video", fields: { subject: "A glass statue shattering into thousands of pieces in extremely slow motion", mood: "dramatic", style: "fluid dynamics, particles flying toward the camera", resolution: "16:9" } },
  { author: "@retro_gamer", model: "SD 1.5", type: "image", difficulty: "beginner", downloads: "750", stars: "280", background: "linear-gradient(135deg, #ff0000, #ffff00)", prompt: "Isometric pixel art of a cozy ramen shop at night, glowing lanterns, detailed tilework, 16-bit aesthetic, nostalgic gaming vibe.", mode: "image", fields: { subject: "Isometric pixel art of a cozy ramen shop at night", mood: "nostalgic", style: "16-bit aesthetic", resolution: "512x512" } },
  { author: "@spooky_tales", model: "Stable Audio", type: "music", difficulty: "intermediate", downloads: "950", stars: "340", background: "linear-gradient(135deg, #3e2723, #1b0000)", prompt: "Creepy horror movie soundtrack, dissonant string scrapes, deep booming low brass, atonal choir whispering, rising tension, terrifying mood.", mode: "music", fields: { subject: "Creepy horror movie soundtrack", mood: "terrifying", style: "dissonant string scrapes", resolution: "1:1" } },
  { author: "@ui_designer", model: "SDXL", type: "image", difficulty: "intermediate", downloads: "1.3k", stars: "490", background: "linear-gradient(135deg, #001133, #00e5ff)", prompt: "Sleek dark mode dashboard UI design for a crypto trading app, glowing green and red charts, glassmorphism elements, clean typography, dribbble style.", mode: "image", fields: { subject: "Sleek dark mode dashboard UI design", mood: "clinical", style: "glassmorphism elements, dribbble style", resolution: "1024x1024" } },
  { author: "@dream_weaver", model: "Flux", type: "image", difficulty: "beginner", downloads: "550", stars: "190", background: "linear-gradient(135deg, #e0c3fc, #8ec5fc)", prompt: "A giant sleeping cat curled up around a miniature village in the clouds, soft fluffy fur, pastel painting style, whimsical storybook illustration.", mode: "image", fields: { subject: "A giant sleeping cat curled up around a miniature village", mood: "happy", style: "whimsical storybook illustration", resolution: "1024x1024" } },
  { author: "@cyber_punk", model: "AnimateDiff", type: "video", difficulty: "advanced", downloads: "1.6k", stars: "580", background: "linear-gradient(135deg, #001133, #00e5ff)", prompt: "First person POV walking through a crowded neon-lit cyberpunk street market, holographic advertisements flickering, steam rising from street food stalls, immersive 3D animation.", mode: "video", fields: { subject: "First person POV walking through a crowded neon-lit cyberpunk street market", mood: "chaotic", style: "immersive 3D animation", resolution: "16:9" } },
  { author: "@jazz_hands", model: "MusicGen", type: "music", difficulty: "beginner", downloads: "800", stars: "270", background: "linear-gradient(135deg, #d4a373, #faedcd)", prompt: "Smooth late night jazz trio, warm upright bass rhythm, brushed snare drums, sultry saxophone melody, intimate club atmosphere, highly dynamic.", mode: "music", fields: { subject: "Smooth late night jazz trio", mood: "intimate", style: "warm upright bass rhythm", resolution: "16:9" } }
];
