import Link from 'next/link';
import Image from 'next/image';
import { notFound, permanentRedirect } from 'next/navigation';
import { CATALOG, compatibilityLabel, workflowKind, workflowKindLabel, WORKFLOW_ASSETS, WORKFLOW_TESTS } from '@/lib/catalog';
import WorkflowCard from '@/components/workflows/WorkflowCard';
import { WorkflowTools } from '@/components/workflows/WorkflowTools';
import { DownloadButton } from '@/components/workflows/DownloadButton';

import { WorkflowCompatibilityInspector } from '@/components/workflows/WorkflowCompatibilityInspector';
import { NewsletterSignup } from '@/components/newsletter/NewsletterSignup';

export function generateStaticParams() { return CATALOG.map(w => ({ id: w.id })); }
export default function WorkflowDetailPage({ params }: { params: { id: string } }) {
  // Workflow IDs are published as two digits (for example, /workflows/07).
  // Redirect a legacy one-digit variant in one hop so it cannot become a
  // duplicate crawl target with a competing canonical.
  if (/^\d$/.test(params.id)) permanentRedirect(`/workflows/0${params.id}`);
  const workflow = CATALOG.find(w => w.id === params.id);
  if (!workflow) notFound();
  const asset = WORKFLOW_ASSETS[workflow.id];
  const test = WORKFLOW_TESTS[workflow.id];
  const nodeSources: Record<string,string> = { 'ADE_AnimateDiffLoaderWithContext':'https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved', 'VHS_VideoCombine':'https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite' };
  const customNodes = asset.nodeTypes.filter(n => nodeSources[n]);
  const related = CATALOG.filter(w => w.id !== workflow.id && w.category === workflow.category).slice(0, 3);
  return <article className="nd-site"><div className="nd-shell nd-page">
    <Link className="nd-text-link" href="/workflows">← All workflows</Link>
    <header className="nd-section"><p className="nd-eyebrow">{workflow.category} / {workflowKindLabel(workflowKind(workflow))} / {workflow.difficulty}</p><h1>{workflow.title}</h1><p className="nd-lead">{workflow.description}</p><div className="nd-actions"><DownloadButton workflowId={workflow.id} workflowTitle={workflow.title} /><a className="nd-button nd-secondary" href="#setup">Read setup instructions</a></div></header>
    <nav className="nd-detail-nav" aria-label="On this page"><a href="#requirements">Requirements</a><a href="#gpu-compatibility">GPU Compatibility</a><a href="#models">Models & nodes</a><a href="#setup">Setup</a><a href="#troubleshooting">Troubleshooting</a><a href="#testing">Test status</a></nav>
    <div className="nd-detail-grid"><div><figure><div className="nd-detail-image">{test?.outputKind === "audio" ? <div className="nd-card-body"><h2>Recorded audio output</h2><audio controls preload="none" src={test.preview} aria-label="Recorded ACE Step test output" /><p>Generated locally with the settings in the test record.</p></div> : test?.outputKind === "video" ? <div className="nd-card-body"><h2>Recorded video output</h2><video controls loop muted playsInline preload="metadata" src={test.preview} aria-label={`Recorded ${workflow.title} video output`} style={{ width: '100%', maxHeight: 512, borderRadius: 8 }} /><p>Generated locally on RTX 5080 with the settings in the test record.</p></div> : <Image src={workflow.imageUrl} alt={test ? `Generated output from the recorded ${workflow.title} test` : `Catalog illustration for ${workflow.title}; not a verified workflow output`} fill priority sizes="(max-width:700px) 100vw, 60vw" className="object-cover" />}</div><figcaption className="nd-subtle">{test ? 'Actual output from the recorded RTX 5080 run. See test settings below.' : 'Catalog illustration. The source does not include evidence tying this image to a run of this JSON.'}</figcaption></figure><section className="nd-section"><h2>What it produces</h2><p>{workflow.longDescription}</p></section></div>
    <section id="requirements" className="nd-card nd-card-body"><p className="nd-eyebrow">HARDWARE & SETTINGS</p><h2>{compatibilityLabel(workflow)}</h2><p>This is a catalog estimate, not a tested minimum. GPU architecture, precision, resolution and offloading affect whether a run fits.</p><dl><dt>Output settings</dt><dd>{test?.resolution || "See graph settings below"}</dd><dt>Workflow version</dt><dd>{workflow.version}</dd><dt>System RAM</dt><dd>{test ? `${Math.round(test.systemRamBytes / 1024 ** 3)} GB (test system)` : "Not documented"}</dd><dt>Test hardware</dt><dd>{test ? "RTX 5080 · 16 GB" : "No recorded run"}</dd><dt>Generation time</dt><dd>{test ? `${test.generationSeconds.toFixed(2)} seconds in this run` : "Not measured"}</dd><dt>Peak memory</dt><dd>Not measured</dd></dl><Link className="nd-text-link" href="/compatibility">Read the compatibility policy →</Link></section></div>
    <WorkflowCompatibilityInspector workflow={workflow} />
    <section id="models" className="nd-section"><h2>Models & custom nodes</h2><p>These model filenames are extracted from the downloadable graph, including subgraphs. Check each source’s license and access requirements.</p><div className="nd-detail-grid"><div>{asset.models.map(m => <div key={m.file} className="nd-dependency"><span>{m.downloadUrl ? <a className="nd-text-link" href={m.downloadUrl} target="_blank" rel="noopener noreferrer">{m.file} ↗</a> : <>{m.file}<p className="nd-subtle">Exact download source still needs confirmation. Do not substitute an unrelated model.</p></>}</span><code>{m.dir}</code></div>)}</div><div className="nd-card nd-card-body"><h3>Custom nodes</h3>{customNodes.length ? <ul>{customNodes.map(n => <li key={n}><a className="nd-text-link" href={nodeSources[n]}>{n} ↗</a><p className="nd-subtle">Use the repository’s installation instructions. No node version has been execution-tested for this entry.</p></li>)}</ul> : <p>The graph uses ComfyUI core nodes. Use a recent ComfyUI version that includes these node types.</p>}<p className="nd-subtle">{asset.hasSubgraphs ? "This graph contains subgraphs and needs a frontend with subgraph support." : "Standard ComfyUI graph."}</p><Link className="nd-text-link" href="/guides/custom-nodes">Custom node setup guide →</Link></div></div></section>
    <section id="setup" className="nd-section nd-prose"><h2>Installation & first run</h2><ol><li>Install ComfyUI using the <a className="nd-text-link" href="https://docs.comfy.org/installation/system_requirements">official requirements and installation documentation</a> for your operating system and GPU.</li><li>Download this workflow JSON. Use the listed model sources above and place the required files in the indicated model folders. <Link className="nd-text-link" href="/guides/model-folders">Model folder guide →</Link></li><li>Load the JSON in ComfyUI. Resolve missing nodes and select installed model files in the loader nodes. Supply any required input image, video or audio.</li><li>Review the graph’s settings before running. See the settings extracted below; a recorded test only establishes the specific configuration used in that run.</li><li>Run the workflow and check the ComfyUI console if it fails. Keep the exact error text, software versions and your hardware details for troubleshooting.</li></ol><h3>Example prompt from the catalog</h3><pre>{workflow.proofPrompt}</pre><p className="nd-subtle">This prompt is a starting point, not evidence that the preview was produced by this workflow.</p></section>
    <WorkflowTools workflow={workflow} />
    <section id="troubleshooting" className="nd-section nd-prose"><h2>When a run fails</h2><details><summary>Missing model or a model name is not available</summary><p>Compare the graph’s loader file names with your installed files and the dependency list. <Link className="nd-text-link" href="/guides/model-folders">Check model folders →</Link></p></details><details><summary>Missing or unrecognized node type</summary><p>Record the exact node type and check its source and version before installing extensions. <Link className="nd-text-link" href="/guides/custom-nodes">Custom node guide →</Link></p></details><details><summary>GPU memory or execution error</summary><p>The VRAM estimate is not a guarantee. Record the error, input dimensions, model precision and batch size. <Link className="nd-text-link" href="/guides/gpu-errors">GPU error guide →</Link> · <Link className="nd-text-link" href="/guides/workflow-errors">Workflow error guide →</Link></p></details></section>
    <section className="nd-section nd-prose"><h2>Graph settings & required inputs</h2>{asset.inputFiles.length > 0 ? <p>Supply your own input files in the Load Image nodes: {asset.inputFiles.join(', ')}. Inpainting needs a prepared mask; ControlNet graphs need a prepared control map matching the model.</p> : <p>No Load Image input file is required by this graph.</p>}<details><summary>View the graph’s saved controls</summary>{asset.settings.map((s,i) => <div key={i} className="nd-dependency"><strong>{s.node} · node {s.id}</strong><pre>{JSON.stringify(s.values)}</pre></div>)}</details></section>
    <section id="testing" className="nd-section nd-prose"><h2>Testing & source information</h2>{test ? <><p>This exact download completed a local run on an RTX 5080 with 16 GB VRAM. This does not establish a minimum VRAM requirement.</p><dl><dt>Test date</dt><dd>{test.testDate.slice(0,10)}</dd><dt>ComfyUI</dt><dd>{test.comfyUI}</dd><dt>PyTorch</dt><dd>{test.pytorch}</dd><dt>Resolution / batch</dt><dd>{test.resolution || "Graph default"} / {test.batchSize ?? 1}</dd>{test.settings?.steps != null && <><dt>Steps / CFG</dt><dd>{String(test.settings.steps)} / {String(test.settings.cfg)}</dd></>}{test.settings?.sampler_name != null && <><dt>Sampler / scheduler</dt><dd>{String(test.settings.sampler_name)} / {String(test.settings.scheduler)}</dd></>}{test.settings?.seed != null && <><dt>Seed</dt><dd>{String(test.settings.seed)}</dd></>}<dt>Generation time</dt><dd>{test.generationSeconds.toFixed(2)} seconds, including model loading</dd><dt>Peak memory</dt><dd>Not measured</dd></dl><a className="nd-text-link" href={`/workflow-tests/${workflow.id}-record.json`}>Download the test record →</a></> : <p>No completed run is recorded for this entry. Graph checks do not establish successful generation. GPU test hardware, measured runtime, peak memory and supported software versions remain unverified.</p>}<p>Catalog version: {workflow.version}. Original publication date is not recorded.</p><p>Graph source: {asset.source.startsWith('https://') ? <a className="nd-text-link" href={asset.source}>{asset.sourceAsset} ↗</a> : asset.source}. {asset.license && <a className="nd-text-link" href={asset.license}>Upstream license</a>}</p><Link className="nd-text-link" href="/compatibility">What a complete test record includes →</Link></section>
    <section className="nd-section"><h2>Related workflows</h2><div className="nd-grid">{related.map(w => <WorkflowCard key={w.id} workflow={w} />)}</div></section>
    <NewsletterSignup source="workflow_detail" />
  </div></article>;
}
