// lib/workflowsData.ts
// Metadata for all 50 neuraldrift ComfyUI workflows
// JSON files live in: public/workflows/{slug}.json

export type WorkflowCategory =
  | "image"
  | "video"
  | "enhance"
  | "controlnet"
  | "lora"
  | "specialty";
export type VRAMTier = "4GB" | "6GB" | "8GB" | "10GB" | "12GB" | "16GB" | "24GB";
export type DifficultyLevel = "Beginner" | "Intermediate" | "Advanced";

export interface WorkflowEntry {
  id: string; // file slug, e.g. "01"
  title: string;
  description: string;
  longDescription: string;
  category: WorkflowCategory;
  vram: VRAMTier;
  difficulty: DifficultyLevel;
  model: string;
  modelPaths: { file: string; dir: string; downloadUrl: string }[];
  customNodes: string[]; // required custom nodes
  genTime: string; // e.g. "~22s on RTX 5080"
  resolution: string; // e.g. "1024×1024"
  tags: string[];
  version: string;
  featured?: boolean;
  imageUrl: string;      // Official output image from comfyanonymous.github.io
  altImages?: { url: string; label: string }[];  // Alternate images
  workflowJsonUrl?: string | null;  // Direct JSON download URL
  proofPrompt: string;
  proTip?: string;
}

const BASE = "https://comfyanonymous.github.io/ComfyUI_examples";

export const WORKFLOWS: WorkflowEntry[] = [
  {
    id: "01", title: "Flux.1 Dev — Text to Image",
    description: "The gold-standard text-to-image pipeline. Separate UNETLoader architecture. Best open-source image quality as of 2026.",
    longDescription: "Flux.1 Dev produces the highest quality images of any open-source model. Uses UNETLoader + DualCLIPLoader (T5-XXL + CLIP-L) architecture. Tuned for 16GB VRAM cards. Perfect starting point for portrait, landscape, and concept generation.",
    category: "image", vram: "16GB", difficulty: "Beginner",
    model: "flux1-dev.safetensors",
    modelPaths: [
      { file: "flux1-dev.safetensors", dir: "ComfyUI/models/unet/", downloadUrl: "https://huggingface.co/black-forest-labs/FLUX.1-dev" },
      { file: "t5xxl_fp16.safetensors", dir: "ComfyUI/models/text_encoders/", downloadUrl: "https://huggingface.co/comfyanonymous/flux_text_encoders/tree/main" },
      { file: "clip_l.safetensors", dir: "ComfyUI/models/text_encoders/", downloadUrl: "https://huggingface.co/comfyanonymous/flux_text_encoders/tree/main" },
      { file: "ae.safetensors", dir: "ComfyUI/models/vae/", downloadUrl: "https://huggingface.co/black-forest-labs/FLUX.1-dev" },
    ],
    customNodes: [],
    genTime: "~22s on RTX 5080", resolution: "1024×1024",
    tags: ["flux", "text-to-image", "portrait", "photorealistic", "16gb"],
    version: "v1.0", featured: true,
    imageUrl: `/workflow-thumbs/01.png`,
    workflowJsonUrl: null,
    altImages: [{ url: `${BASE}/flux/flux_dev_checkpoint_example.png`, label: "FP8 checkpoint version — 12GB VRAM" }],
    proofPrompt: "Cinematic portrait of a weathered astronaut in a retro 1960s spacesuit, dramatic rim lighting, film grain, analog photography, shallow depth of field",
    proTip: "Reduce T5-XXL to fp8 to save 4GB VRAM with minimal quality loss."
  },
  {
    id: "02", title: "Flux.1 Schnell — 4-Step Fast",
    description: "4-step distilled Flux. Full quality in under 6 seconds. Use for rapid prompt iteration.",
    longDescription: "Flux Schnell with 4-step distillation. CFG 1.0, Euler sampler, simple scheduler. Ideal for iterating prompts quickly before switching to Dev for final renders. FP8 checkpoint compatible with 8GB VRAM.",
    category: "image", vram: "8GB", difficulty: "Beginner",
    model: "flux1-schnell-fp8.safetensors",
    modelPaths: [{ file: "flux1-schnell-fp8.safetensors", dir: "ComfyUI/models/checkpoints/", downloadUrl: "https://huggingface.co/Comfy-Org/flux1-schnell" }],
    customNodes: [], genTime: "~5s on RTX 5080", resolution: "1024×1024",
    tags: ["flux", "schnell", "fast", "4-step", "8gb"],
    version: "v1.0", featured: true,
    imageUrl: `/workflow-thumbs/02.png`,
    workflowJsonUrl: null,
    altImages: [{ url: `${BASE}/flux/flux_schnell_checkpoint_example.png`, label: "Schnell FP8 checkpoint variant" }],
    proofPrompt: "Aerial view of a futuristic city at golden hour, neon signs, flying vehicles, ultra detailed",
    proTip: "Perfect for rapid testing; use Euler sampler and CFG 1.0 for the fastest 4-step convergence."
  },
  {
    id: "03", title: "SDXL Base + Refiner",
    description: "Classic SDXL two-pass pipeline. Base generates the latent, Refiner adds fine detail at 1024px.",
    longDescription: "Battle-tested SDXL workflow. Base generates at 1024px, Refiner pass adds fine details. The established template for high-quality SDXL generation. Works on 8GB cards.",
    category: "image", vram: "8GB", difficulty: "Beginner",
    model: "sd_xl_base_1.0.safetensors",
    modelPaths: [
      { file: "sd_xl_base_1.0.safetensors", dir: "ComfyUI/models/checkpoints/", downloadUrl: "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0" },
      { file: "sd_xl_refiner_1.0.safetensors", dir: "ComfyUI/models/checkpoints/", downloadUrl: "https://huggingface.co/stabilityai/stable-diffusion-xl-refiner-1.0" },
    ],
    customNodes: [], genTime: "~35s on RTX 5080", resolution: "1024×1024",
    tags: ["sdxl", "text-to-image", "two-pass", "8gb", "refiner"],
    version: "v1.0",
    imageUrl: `/workflow-thumbs/03.png`,
    workflowJsonUrl: null,
    altImages: [
      { url: `${BASE}/sdxl/sdxl_refiner_prompt_example.png`, label: "SDXL with separate base/refiner prompts" },
      { url: `${BASE}/sdxl/sdxl_revision_zero_positive.png`, label: "SDXL ReVision — image-guided generation" },
    ],
    proofPrompt: "Epic fantasy dragon perched on a mountain peak, storm clouds, lightning, hyper detailed scales, fantasy art",
    proTip: "Layer the Refiner at 0.2 denoise to add high-frequency skin texture without altering the base composition."
  },
  {
    id: "04", title: "Stable Diffusion 1.5 Default",
    description: "The original ComfyUI default workflow. 4GB VRAM. Every node teaches a core concept.",
    longDescription: "The ComfyUI default workflow. SD 1.5 baseline — runs on any GPU with 4GB VRAM. Essential for learning the graph structure. Every node teaches a fundamental ComfyUI concept.",
    category: "image", vram: "4GB", difficulty: "Beginner",
    model: "v1-5-pruned-emaonly.safetensors",
    modelPaths: [{ file: "v1-5-pruned-emaonly.safetensors", dir: "ComfyUI/models/checkpoints/", downloadUrl: "https://huggingface.co/stable-diffusion-v1-5/stable-diffusion-v1-5" }],
    customNodes: [], genTime: "~12s on RTX 5080", resolution: "512×512",
    tags: ["sd15", "beginner", "default", "4gb", "learning"],
    version: "v1.0",
    imageUrl: `/workflow-thumbs/04.png`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "A wise old wizard in a tower library surrounded by glowing spell books, dramatic lighting, detailed fantasy",
    proTip: "Great starting point. Drag any output image back into ComfyUI to reload the exact settings used."
  },
  {
    id: "05", title: "HiDream — 17B Text to Image",
    description: "HiDream-I1 17B parameter model. State-of-the-art image quality in 2025. 4 text encoders.",
    longDescription: "HiDream I1 uses 4 text encoders (CLIP-L, CLIP-G, T5, LLaMA 3.1 8B). One of the most capable open-source image models available. Exceptional prompt adherence and photorealism.",
    category: "image", vram: "16GB", difficulty: "Intermediate",
    model: "hidream_i1_dev_bf16.safetensors",
    modelPaths: [
      { file: "hidream_i1_dev_bf16.safetensors", dir: "ComfyUI/models/diffusion_models/", downloadUrl: "https://huggingface.co/Comfy-Org/HiDream-I1_ComfyUI" },
      { file: "clip_l_hidream.safetensors", dir: "ComfyUI/models/text_encoders/", downloadUrl: "https://huggingface.co/Comfy-Org/HiDream-I1_ComfyUI" },
      { file: "clip_g_hidream.safetensors", dir: "ComfyUI/models/text_encoders/", downloadUrl: "https://huggingface.co/Comfy-Org/HiDream-I1_ComfyUI" },
      { file: "t5xxl_fp8_e4m3fn_scaled.safetensors", dir: "ComfyUI/models/text_encoders/", downloadUrl: "https://huggingface.co/Comfy-Org/HiDream-I1_ComfyUI" },
      { file: "llama_3.1_8b_instruct_fp8_scaled.safetensors", dir: "ComfyUI/models/text_encoders/", downloadUrl: "https://huggingface.co/Comfy-Org/HiDream-I1_ComfyUI" },
      { file: "ae.safetensors", dir: "ComfyUI/models/vae/", downloadUrl: "https://huggingface.co/Comfy-Org/HiDream-I1_ComfyUI" },
    ],
    customNodes: [], genTime: "~40s on RTX 5080", resolution: "1024×1024",
    tags: ["hidream", "17b", "text-to-image", "16gb", "state-of-the-art"],
    version: "v1.0",
    imageUrl: `/workflow-thumbs/05.png`,
    workflowJsonUrl: null,
    altImages: [
      { url: `${BASE}/hidream/hidream_full_example.png`, label: "HiDream Full FP16 — maximum quality" },
      { url: `${BASE}/hidream/hidream_e1.1_example.png`, label: "HiDream e1.1 — instruction edit model" },
    ],
    proofPrompt: "Product photography: luxury wristwatch on marble surface, studio lighting, water droplets, macro lens, commercial quality",
    proTip: "Use the LLaMA 3.1 8B encoder for the best natural language prompt adherence."
  },
  {
    id: "06", title: "Hunyuan Image 2.1",
    description: "Tencent Hunyuan DiT 2.1. Exceptional bilingual (Chinese + English) prompt support.",
    longDescription: "Tencent's Hunyuan DiT 2.1. Strong bilingual prompt support (Chinese and English). Excellent for architectural, portrait, and landscape generation.",
    category: "image", vram: "12GB", difficulty: "Intermediate",
    model: "hunyuan-dit-v1.2.safetensors",
    modelPaths: [{ file: "hunyuan-dit-v1.2.safetensors", dir: "ComfyUI/models/checkpoints/", downloadUrl: "https://huggingface.co/Tencent-Hunyuan/HunyuanDiT-v1.2-Diffusers" }],
    customNodes: [], genTime: "~30s on RTX 5080", resolution: "1024×1024",
    tags: ["hunyuan", "bilingual", "12gb", "text-to-image"],
    version: "v1.0",
    imageUrl: `/workflow-thumbs/06.png`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "Traditional Japanese tea ceremony in a zen garden, cherry blossoms, golden light, ultra detailed, photography",
    proTip: "The bilingual support allows for very nuanced cultural descriptions that other models might miss."
  },
  {
    id: "07", title: "Lumina Image 2.0",
    description: "Shanghai AI Lab flow-matching model. Fast convergence, strong aesthetic quality. 10GB VRAM.",
    longDescription: "Lumina Image 2.0 from Shanghai AI Lab. Fast training convergence, strong aesthetic. Competitive with Flux in the 10-12GB VRAM range. Good for abstract and artistic generation.",
    category: "image", vram: "10GB", difficulty: "Intermediate",
    model: "lumina_image_2.0.safetensors",
    modelPaths: [{ file: "lumina_image_2.0.safetensors", dir: "ComfyUI/models/checkpoints/", downloadUrl: "https://huggingface.co/Alpha-VLLM/Lumina-Image-2.0" }],
    customNodes: [], genTime: "~25s on RTX 5080", resolution: "1024×1024",
    tags: ["lumina", "flow-matching", "10gb", "artistic"],
    version: "v1.0",
    imageUrl: `/workflow-thumbs/07.png`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "Abstract neon sculpture in a dark void, liquid chrome surfaces, reflection, studio art photography",
    proTip: "Excellent for abstract concepts; try focusing on lighting and materials."
  },
  {
    id: "08", title: "Qwen Image Edit (Multimodal)",
    description: "Qwen 2.5 VL 7B multimodal editor. Natural language image instructions. Understands scene content.",
    longDescription: "Qwen VL multimodal image editing — give natural language instructions like 'make it raining' or 'change the era to 1970s'. The model understands scene content and edits intelligently.",
    category: "image", vram: "16GB", difficulty: "Intermediate",
    model: "qwen_image_fp8_e4m3fn.safetensors",
    modelPaths: [
      { file: "qwen_image_fp8_e4m3fn.safetensors", dir: "ComfyUI/models/diffusion_models/", downloadUrl: "https://huggingface.co/Comfy-Org/Qwen2.5-VL-7B-Instruct_ComfyUI" },
      { file: "qwen_2.5_vl_7b_fp8_scaled.safetensors", dir: "ComfyUI/models/text_encoders/", downloadUrl: "https://huggingface.co/Comfy-Org/Qwen2.5-VL-7B-Instruct_ComfyUI" },
    ],
    customNodes: [], genTime: "~35s on RTX 5080", resolution: "1024×1024",
    tags: ["qwen", "multimodal", "image-edit", "16gb", "instruction"],
    version: "v1.0",
    imageUrl: `/workflow-thumbs/08.png`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "Input: any photo. Instruction: Make this look like a vintage 1970s polaroid with faded colors and light leaks",
    proTip: "Use conversational instructions rather than technical keywords for this model."
  },
  {
    id: "09", title: "Chroma — Stylized No-Negative",
    description: "Chroma model variant. No negative prompt needed. Strong for illustration and creative content.",
    longDescription: "Chroma model trained without negative prompt support. Simplified pipeline. Strong at stylized illustration and creative content generation. Uncensored, open-source.",
    category: "image", vram: "12GB", difficulty: "Intermediate",
    model: "chroma-unlocked.safetensors",
    modelPaths: [{ file: "chroma-unlocked.safetensors", dir: "ComfyUI/models/unet/", downloadUrl: "https://huggingface.co/lodestone-rock/chroma" }],
    customNodes: [], genTime: "~20s on RTX 5080", resolution: "1024×1024",
    tags: ["chroma", "no-negative", "illustration", "12gb", "creative"],
    version: "v1.0",
    imageUrl: `/workflow-thumbs/09.png`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "Surreal landscape with floating islands, bioluminescent plants, twin moons, stylized illustration",
    proTip: "Since no negative is needed, focus all your tokens on descriptive positive attributes."
  },
  {
    id: "10", title: "AuraFlow Text to Image",
    description: "AuraFlow v0.3. Fast open-source flow-matching. Competitive quality in under 30 steps. 8GB.",
    longDescription: "AuraFlow v0.3 — fast open-source flow-matching model. Good quality in under 30 steps. Lower VRAM than Flux while still competitive. Good for cozy, atmospheric scenes.",
    category: "image", vram: "8GB", difficulty: "Beginner",
    model: "aura_flow.safetensors",
    modelPaths: [{ file: "aura_flow.safetensors", dir: "ComfyUI/models/checkpoints/", downloadUrl: "https://huggingface.co/fal/AuraFlow" }],
    customNodes: [], genTime: "~18s on RTX 5080", resolution: "1024×1024",
    tags: ["auraflow", "flow-matching", "8gb", "fast"],
    version: "v1.0",
    imageUrl: `/workflow-thumbs/10.png`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "Cozy cabin interior in winter, fireplace glowing, snow visible through frosted windows, warm light",
    proTip: "Excellent for atmospheric lighting; use words like 'ambient glow' and 'soft shadows'."
  },
  {
    id: "11", title: "LTX Video 2.3 — Basic T2V",
    description: "LTX Video 2.3 text-to-video. 25 frames, 768×512, 20 steps. Entry-level video generation.",
    longDescription: "The simplest LTX Video workflow. 25 frames at 768×512 generates a ~2-second clip at 12fps. Uses LTXVSampler with DPM++ 2M and linear scheduler. CFG 3.5 for balanced prompt adherence. Requires ComfyUI-LTXVideo and VideoHelperSuite custom nodes.",
    category: "video", vram: "12GB", difficulty: "Beginner",
    model: "ltx-video-2b-v0.9.5.safetensors",
    modelPaths: [{ file: "ltx-video-2b-v0.9.5.safetensors", dir: "ComfyUI/models/checkpoints/", downloadUrl: "https://huggingface.co/Lightricks/LTX-Video" }],
    customNodes: ["ComfyUI-LTXVideo", "ComfyUI-VideoHelperSuite"],
    genTime: "~25s on RTX 5080", resolution: "768×512",
    tags: ["LTX Video", "video", "t2v", "12GB", "beginner"],
    version: "v2.3", featured: true,
    imageUrl: `/workflow-thumbs/11.png`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "A majestic eagle soaring over snow-capped mountains at sunset, detailed cinematic video",
    proTip: "For the most stable motion, keep the CFG between 3.0 and 4.0."
  },
  {
    id: "12", title: "LTX Video — Cinematic 9:16",
    description: "97-frame vertical video at 768×1344 for YouTube Shorts and TikTok. Motion scale 1.2.",
    longDescription: "Full cinematic vertical video workflow. 97 frames = ~8 seconds at 12fps. 768×1344 resolution for native 9:16 Shorts format. Motion scale 1.2 adds cinematic momentum without instability. 25 steps, DPM++ 2M scheduler. RTX 5080 generates in ~47 seconds.",
    category: "video", vram: "16GB", difficulty: "Intermediate",
    model: "ltx-video-2b-v0.9.5.safetensors",
    modelPaths: [{ file: "ltx-video-2b-v0.9.5.safetensors", dir: "ComfyUI/models/checkpoints/", downloadUrl: "https://huggingface.co/Lightricks/LTX-Video" }],
    customNodes: ["ComfyUI-LTXVideo", "ComfyUI-VideoHelperSuite"],
    genTime: "~47s on RTX 5080", resolution: "768×1344",
    tags: ["LTX Video", "cinematic", "shorts", "9:16", "16GB"],
    version: "v2.3", featured: true,
    imageUrl: `/workflow-thumbs/12.png`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "Cyberpunk street at night, neon lights reflecting in puddles, rain, vertical 9:16 composition",
    proTip: "9:16 aspect ratio is perfect for mobile viewers; use vertical framing prompts."
  },
  {
    id: "13", title: "LTX Video — Action Chase",
    description: "High motion chase sequence. 97 frames, motion scale 1.4 for maximum kinetic energy.",
    longDescription: "Maximum motion chaos workflow for chase and action scenes. Motion scale pushed to 1.4 creates aggressive frame-to-frame movement. Pre-loaded chase prompt with GoPro POV cues. Pairs with the 5-clip series arc from the LTX Video cinematic guide. RTX 5080 optimized.",
    category: "video", vram: "16GB", difficulty: "Advanced",
    model: "ltx-video-2b-v0.9.5.safetensors",
    modelPaths: [{ file: "ltx-video-2b-v0.9.5.safetensors", dir: "ComfyUI/models/checkpoints/", downloadUrl: "https://huggingface.co/Lightricks/LTX-Video" }],
    customNodes: ["ComfyUI-LTXVideo", "ComfyUI-VideoHelperSuite"],
    genTime: "~47s on RTX 5080", resolution: "768×1344",
    tags: ["LTX Video", "action", "chase", "GoPro", "motion"],
    version: "v2.3", featured: true,
    imageUrl: `/workflow-thumbs/13.png`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "First-person view of a high-speed car chase through a desert, dust kicking up, intense motion",
    proTip: "Increase motion scale to 1.4 for faster action in LTX Video, but expect some minor artifacts."
  },
  {
    id: "14", title: "LTX Video — Fast Draft",
    description: "15-step, 25-frame draft generation for prompt testing before committing to full renders.",
    longDescription: "Low-resource draft workflow for validating LTX Video prompts. 25 frames, 512×512, 15 steps at CFG 3.0. Generate a preview in under 15 seconds before committing to a full 97-frame cinematic render. Motion scale 0.8 for stable preview output.",
    category: "video", vram: "12GB", difficulty: "Beginner",
    model: "ltx-video-2b-v0.9.5.safetensors",
    modelPaths: [{ file: "ltx-video-2b-v0.9.5.safetensors", dir: "ComfyUI/models/checkpoints/", downloadUrl: "https://huggingface.co/Lightricks/LTX-Video" }],
    customNodes: ["ComfyUI-LTXVideo", "ComfyUI-VideoHelperSuite"],
    genTime: "~12s on RTX 5080", resolution: "512×512",
    tags: ["LTX Video", "draft", "fast", "preview", "12GB"],
    version: "v2.3",
    imageUrl: `/workflow-thumbs/14.png`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "A simple animation of a growing flower, time-lapse, draft quality",
    proTip: "Drafters save hours of time; refine your prompt at 512px before going to 1024px."
  },
  {
    id: "15", title: "AnimateDiff Simple Loop",
    description: "SD 1.5 + AnimateDiff v3 motion module. 16 frames, 512×512 seamless loop. 8GB compatible.",
    longDescription: "The foundational AnimateDiff workflow. SD 1.5 model + mm_sd_v15_v3.ckpt motion module + KSampler. 16 frames at 8fps = 2-second seamless loop. Exports as MP4 via VideoHelperSuite. Works on 8GB cards. Base template for all other AnimateDiff workflows.",
    category: "video", vram: "8GB", difficulty: "Beginner",
    model: "realisticVisionV60B1_v60B1VAE.safetensors",
    modelPaths: [
      { file: "realisticVisionV60B1_v60B1VAE.safetensors", dir: "ComfyUI/models/checkpoints/", downloadUrl: "https://huggingface.co/SG_161222/Realistic_Vision_V6.0_B1_noVAE" },
      { file: "mm_sd_v15_v3.ckpt", dir: "ComfyUI/models/animatediff_models/", downloadUrl: "https://huggingface.co/guoyww/animatediff/tree/main" }
    ],
    customNodes: ["ComfyUI-AnimateDiff-Evolved", "ComfyUI-VideoHelperSuite"],
    genTime: "~45s on RTX 5080", resolution: "512×512",
    tags: ["AnimateDiff", "loop", "SD1.5", "8GB", "beginner"],
    version: "v2.0", featured: true,
    imageUrl: `/workflow-thumbs/15.png`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "A floating magical orb in a dark forest, particles swirling around it, seamless loop",
    proTip: "For SD 1.5 AnimateDiff, the v3 motion module provides the smoothest transitions."
  },
  {
    id: "16", title: "AnimateDiff Seamless Loop",
    description: "Infinite seamless loop optimized for social media. Glowing particle preset, 16 frames.",
    longDescription: "Engineered for perfect looping content. Uses AnimateDiff's loop mode to align first and last frames. 16 frames at 8fps creates a 2-second infinite loop for Instagram Reels. VHS_VideoCombine set to loop_count=0. Pre-loaded with particle/ambient motion prompts.",
    category: "video", vram: "8GB", difficulty: "Intermediate",
    model: "dreamshaper_8.safetensors",
    modelPaths: [
      { file: "dreamshaper_8.safetensors", dir: "ComfyUI/models/checkpoints/", downloadUrl: "https://huggingface.co/Lykon/DreamShaper" },
      { file: "mm_sd_v15_v2.ckpt", dir: "ComfyUI/models/animatediff_models/", downloadUrl: "https://huggingface.co/guoyww/animatediff/tree/main" }
    ],
    customNodes: ["ComfyUI-AnimateDiff-Evolved", "ComfyUI-VideoHelperSuite"],
    genTime: "~40s on RTX 5080", resolution: "512×512",
    tags: ["AnimateDiff", "loop", "ambient", "Instagram", "8GB"],
    version: "v2.0",
    imageUrl: `/workflow-thumbs/16.png`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "Abstract liquid metal flowing in a vacuum, glowing particles, loop",
    proTip: "Use the `Context Options` node to manage longer animations without running out of VRAM."
  },
  {
    id: "17", title: "AnimateDiff Landscape Timelapse",
    description: "Cinematic timelapse animation. 24 frames, cloud movement pre-prompted.",
    longDescription: "Landscape timelapse workflow using AnimateDiff SDXL motion module. 24 frames for longer, smoother motion. Cloud and fog movement prompts drive the animation. Exports as 24fps MP4 for cinematic feel. Requires mm_sdxl_v10_beta motion module.",
    category: "video", vram: "12GB", difficulty: "Intermediate",
    model: "realisticVisionV60B1_v60B1VAE.safetensors",
    modelPaths: [{ file: "mm_sdxl_v10_beta.safetensors", dir: "ComfyUI/models/animatediff_models/", downloadUrl: "https://huggingface.co/guoyww/AnimateDiff/tree/main" }],
    customNodes: ["ComfyUI-AnimateDiff-Evolved", "ComfyUI-VideoHelperSuite"],
    genTime: "~2m on RTX 5080", resolution: "512×512",
    tags: ["AnimateDiff", "timelapse", "landscape", "clouds", "12GB"],
    version: "v2.0",
    imageUrl: `/workflow-thumbs/17.png`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "Mountain range at sunrise, clouds moving rapidly through the peaks, timelapse photography",
    proTip: "Force the frame rate to 24fps in Video Combine for a more professional cinematic look."
  },
  {
    id: "18", title: "AnimateDiff 360 Product Spin",
    description: "Smooth 360-degree product rotation for e-commerce and marketing content.",
    longDescription: "Product showcase workflow with studio lighting prompts and smooth rotation animation. 24 frames, white background, controlled spin motion. Uses DPM++ 2M Karras for clean, artifact-free studio renders. Ideal for e-commerce product pages and social media ads.",
    category: "video", vram: "10GB", difficulty: "Intermediate",
    model: "deliberate_v6.safetensors",
    modelPaths: [{ file: "deliberate_v6.safetensors", dir: "ComfyUI/models/checkpoints/", downloadUrl: "https://huggingface.co/XpucT/Deliberate" }],
    customNodes: ["ComfyUI-AnimateDiff-Evolved", "ComfyUI-VideoHelperSuite"],
    genTime: "~2m on RTX 5080", resolution: "512×512",
    tags: ["AnimateDiff", "product", "360", "e-commerce", "10GB"],
    version: "v1.0",
    imageUrl: `/workflow-thumbs/18.png`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "A sleek modern coffee machine rotating 360 degrees on a white pedestal, studio lighting",
    proTip: "ControlNet Depth can help keep the product shape stable during the 360-degree rotation."
  },
  {
    id: "19", title: "AnimateDiff Slow Zoom",
    description: "Cinematic slow zoom into a scene. 16 frames, wide landscape format, dramatic fog.",
    longDescription: "Cinematic zoom-in effect using AnimateDiff motion guidance. 16 frames at 768×512 landscape format. Fog and atmospheric depth prompts enhance the zoom illusion. DPM++ 2M at 20 steps for clean motion. Works well for documentary-style openers.",
    category: "video", vram: "10GB", difficulty: "Intermediate",
    model: "dreamshaper_8.safetensors",
    modelPaths: [{ file: "dreamshaper_8.safetensors", dir: "ComfyUI/models/checkpoints/", downloadUrl: "https://huggingface.co/Lykon/DreamShaper" }],
    customNodes: ["ComfyUI-AnimateDiff-Evolved", "ComfyUI-VideoHelperSuite"],
    genTime: "~1m 30s on RTX 5080", resolution: "768×512",
    tags: ["AnimateDiff", "zoom", "cinematic", "fog", "10GB"],
    version: "v1.0",
    imageUrl: `/workflow-thumbs/19.png`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "Approaching a dark mysterious castle on a cliff, heavy fog, slow cinematic zoom",
    proTip: "Add 'atmospheric perspective' to your prompt to make the zoom feel much more deep and realistic."
  },
  {
    id: "20", title: "Wan 2.1 Video — 480p T2V",
    description: "Alibaba Wan 2.1 480p text-to-video. State-of-the-art transformer video generation.",
    longDescription: "Wan 2.1 is the new standard for open-source video. This workflow generates 480p clips with exceptional motion stability. Requires wan-2.1-t2v-1.3b.safetensors. Optimized for 12GB+ cards.",
    category: "video", vram: "12GB", difficulty: "Intermediate",
    model: "wan-2.1-t2v-1.3b.safetensors",
    modelPaths: [{ file: "wan-2.1-t2v-1.3b.safetensors", dir: "ComfyUI/models/checkpoints/", downloadUrl: "https://huggingface.co/Wan-AI/Wan2.1-T2V-1.3B" }],
    customNodes: ["ComfyUI-WanVideo", "ComfyUI-VideoHelperSuite"],
    genTime: "~50s on RTX 5080", resolution: "832×480",
    tags: ["Wan 2.1", "video", "t2v", "transformer", "12GB"],
    version: "v1.0", featured: true,
    imageUrl: `/workflow-thumbs/20.png`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "A small robot exploring a colorful coral reef under the ocean, detailed bubbles, smooth motion",
    proTip: "Use 'cinematic quality' and 'smooth motion' to get the best results from the Wan transformer architecture."
  },
  {
    id: "21", title: "4x ESRGAN Upscale",
    description: "RealESRGAN 4x upscale for photorealistic images. Runs on 6GB. Load any image, get 4x output.",
    longDescription: "Drop any image in and get a 4x resolution upscale using RealESRGAN_x4plus. No checkpoint needed — just the upscale model in models/upscale_models/. Works on GTX 1660 Ti. Outputs to SaveImage node. Essential finishing step for all workflows.",
    category: "enhance", vram: "6GB", difficulty: "Beginner",
    model: "RealESRGAN_x4plus.pth",
    modelPaths: [{ file: "RealESRGAN_x4plus.pth", dir: "ComfyUI/models/upscale_models/", downloadUrl: "https://huggingface.co/ai-forever/Real-ESRGAN/tree/main" }],
    customNodes: [], genTime: "~3s on RTX 5080", resolution: "4x input size",
    tags: ["upscale", "ESRGAN", "4x", "6GB", "enhancement"],
    version: "v1.0", featured: true,
    imageUrl: `/workflow-thumbs/21.png`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "Input: 512px photo. Output: 2048px ultra-sharp photorealistic enhancement",
    proTip: "ESRGAN is best for photorealistic images; it can over-sharpen artistic or anime content."
  },
  {
    id: "22", title: "4x Anime Upscale",
    description: "RealESRGAN x4 Anime optimized upscale. Preserves linework and flat colors.",
    longDescription: "Anime-specific upscale using RealESRGAN_x4plus_anime_6B. 6-block architecture preserves crisp linework and flat color regions better than the standard model. Essential for SD 1.5 anime outputs before publishing. 6GB VRAM minimum.",
    category: "enhance", vram: "6GB", difficulty: "Beginner",
    model: "RealESRGAN_x4plus_anime_6B.pth",
    modelPaths: [{ file: "RealESRGAN_x4plus_anime_6B.pth", dir: "ComfyUI/models/upscale_models/", downloadUrl: "https://huggingface.co/ai-forever/Real-ESRGAN/tree/main" }],
    customNodes: [], genTime: "~2s on RTX 5080", resolution: "4x input size",
    tags: ["upscale", "anime", "ESRGAN", "6GB", "linework"],
    version: "v1.0",
    imageUrl: `/workflow-thumbs/22.png`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "Input: 512px anime sketch. Output: 2048px clean, sharp anime illustration",
    proTip: "Use this specific anime model to avoid artifacts on flat color areas."
  },
  {
    id: "23", title: "SDXL Image-to-Image",
    description: "Transform existing images with SDXL. Denoise 0.6 for strong style transfer while preserving composition.",
    longDescription: "Img2img workflow that re-renders your existing images with new style prompts. Denoise at 0.6 preserves ~40% of the original composition. Oil painting preset loaded. Encode input via VAEEncode, decode via VAEDecode. Swap the prompt to change output style entirely.",
    category: "enhance", vram: "8GB", difficulty: "Beginner",
    model: "sd_xl_base_1.0.safetensors",
    modelPaths: [{ file: "sd_xl_base_1.0.safetensors", dir: "ComfyUI/models/checkpoints/", downloadUrl: "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0" }],
    customNodes: [], genTime: "~5s on RTX 5080", resolution: "1024×1024",
    tags: ["img2img", "SDXL", "style transfer", "8GB", "transform"],
    version: "v1.0",
    imageUrl: `/workflow-thumbs/23.png`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "Input: photo of a park. Prompt: A vibrant oil painting of a park in autumn, thick brushstrokes",
    proTip: "A denoise of 0.6 is the sweet spot for changing style without losing the original image shape."
  },
  {
    id: "24", title: "SD 1.5 Style Transfer",
    description: "Aggressive style transfer at denoise 0.75. Cyberpunk preset. Works on 6GB cards.",
    longDescription: "Higher denoise (0.75) for more aggressive style transformation. Dreamshaper v8 handles realistic-to-artistic transitions better than base SD 1.5. Cyberpunk preset applies neon/glowing elements. Reduce denoise to 0.4 for subtle transformations.",
    category: "enhance", vram: "6GB", difficulty: "Beginner",
    model: "dreamshaper_8.safetensors",
    modelPaths: [{ file: "dreamshaper_8.safetensors", dir: "ComfyUI/models/checkpoints/", downloadUrl: "https://huggingface.co/Lykon/DreamShaper" }],
    customNodes: [], genTime: "~3s on RTX 5080", resolution: "512×512",
    tags: ["style transfer", "SD1.5", "cyberpunk", "6GB", "img2img"],
    version: "v1.0",
    imageUrl: `/workflow-thumbs/24.png`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "Input: street photo. Prompt: A high-tech cyberpunk city street, neon signs, rainy night, cinematic",
    proTip: "For SD 1.5, use specialized checkpoints like DreamShaper for much better artistic results."
  },
  {
    id: "25", title: "SDXL Sketch to Photo",
    description: "Turn rough sketches into photorealistic images at denoise 0.85. High fidelity conversion.",
    longDescription: "High denoise (0.85) workflow for maximum transformation from sketch input. SDXL renders photorealistic details from loose line drawings. 25 steps and CFG 7.5 for sharp, detailed output. Load your sketch as the input image. Works best with clear, unambiguous line art.",
    category: "enhance", vram: "8GB", difficulty: "Intermediate",
    model: "sd_xl_base_1.0.safetensors",
    modelPaths: [{ file: "sd_xl_base_1.0.safetensors", dir: "ComfyUI/models/checkpoints/", downloadUrl: "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0" }],
    customNodes: [], genTime: "~6s on RTX 5080", resolution: "1024×1024",
    tags: ["sketch", "img2img", "SDXL", "render", "8GB"],
    version: "v1.0",
    imageUrl: `/workflow-thumbs/25.png`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "Input: crude pencil sketch of a house. Prompt: A luxurious modern villa in the mountains, architectural photography",
    proTip: "Set the denoise to 0.85 to allow the AI to build realistic textures that follow your sketch's lines."
  },
  {
    id: "26", title: "SDXL Inpainting",
    description: "Fill, replace, or repair image regions using mask input. Seamless blending at 1024px.",
    longDescription: "Inpainting workflow using VAEEncodeForInpaint with 6-pixel mask blur for seamless edge blending. Load your image + mask (white = inpaint area). Prompt describes what to fill in. CFG 7.5 for strong content direction. Replace objects, remove elements, extend backgrounds.",
    category: "enhance", vram: "10GB", difficulty: "Intermediate",
    model: "sd_xl_base_1.0.safetensors",
    modelPaths: [{ file: "sd_xl_base_1.0.safetensors", dir: "ComfyUI/models/checkpoints/", downloadUrl: "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0" }],
    customNodes: [], genTime: "~6s on RTX 5080", resolution: "1024×1024",
    tags: ["inpainting", "SDXL", "mask", "fill", "10GB"],
    version: "v1.0",
    imageUrl: `/workflow-thumbs/26.png`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "Input: person standing in a field. Mask: their clothes. Prompt: A futuristic silver spacesuit",
    proTip: "Use a soft brush for your mask to ensure the AI blends the edges naturally with the original image."
  },
  {
    id: "27", title: "SD 1.5 Object Removal",
    description: "Remove objects from images with SD 1.5 inpainting. Clean background fill at 512px.",
    longDescription: "Object removal using the official SD 1.5 inpainting checkpoint. Paint a white mask over what you want removed, set a clean background prompt, and the model fills with matching texture. Lower resolution (512px) for faster iteration. Switch to SDXL inpaint for higher quality.",
    category: "enhance", vram: "6GB", difficulty: "Beginner",
    model: "sd-v1-5-inpainting.ckpt",
    modelPaths: [{ file: "sd-v1-5-inpainting.ckpt", dir: "ComfyUI/models/checkpoints/", downloadUrl: "https://huggingface.co/stable-diffusion-v1-5/stable-diffusion-v1-5" }],
    customNodes: [], genTime: "~3s on RTX 5080", resolution: "512×512",
    tags: ["inpainting", "remove", "SD1.5", "6GB", "cleanup"],
    version: "v1.0",
    imageUrl: `/workflow-thumbs/27.png`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "Input: beach photo with trash on sand. Mask: the trash. Prompt: Clean white sand",
    proTip: "For object removal, keep your prompt very simple: describe only what should be there instead."
  },
  {
    id: "28", title: "SDXL Product Photography",
    description: "Commercial product photography on white background. Studio lighting tuned for clean shots.",
    longDescription: "Product shot workflow with commercial photography prompts. White background, soft-box lighting, sharp focus with shallow depth of field. CFG 7.0, 30 steps for maximum product detail. Ideal for generating mock product imagery or e-commerce assets.",
    category: "specialty", vram: "8GB", difficulty: "Beginner",
    model: "sd_xl_base_1.0.safetensors",
    modelPaths: [{ file: "sd_xl_base_1.0.safetensors", dir: "ComfyUI/models/checkpoints/", downloadUrl: "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0" }],
    customNodes: [], genTime: "~6s on RTX 5080", resolution: "1024×1024",
    tags: ["product", "photography", "commercial", "SDXL", "8GB"],
    version: "v1.0",
    imageUrl: `/workflow-thumbs/28.png`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "Product shot: luxury perfume bottle on a white pedestal, soft studio lighting, high-end commercial style",
    proTip: "Use keywords like 'product photography' and 'centered' to keep the AI focused on the subject."
  },
  {
    id: "29", title: "SDXL Architectural Visualization",
    description: "Professional architectural exterior rendering. Daylight, photorealistic, ultra-detailed.",
    longDescription: "Architecture workflow tuned for exterior building visualization. Daylight photography prompts with professional architectural framing. 30 steps, CFG 7.5 for precise structural detail. Useful for rapid architecture concept visualization before full 3D rendering.",
    category: "specialty", vram: "8GB", difficulty: "Beginner",
    model: "sd_xl_base_1.0.safetensors",
    modelPaths: [{ file: "sd_xl_base_1.0.safetensors", dir: "ComfyUI/models/checkpoints/", downloadUrl: "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0" }],
    customNodes: [], genTime: "~6s on RTX 5080", resolution: "1024×1024",
    tags: ["architecture", "visualization", "SDXL", "exterior", "8GB"],
    version: "v1.0",
    imageUrl: `/workflow-thumbs/29.png`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "Modern glass house in a forest at sunset, architectural photography, hyper-realistic rendering",
    proTip: "Vertical lines are critical in architecture; use 'straight vertical lines' to keep the buildings from leaning."
  },
  {
    id: "30", title: "FLUX Portrait v2 — Editorial",
    description: "High-contrast editorial portrait workflow using FLUX fp8. Vogue-style lighting.",
    longDescription: "Editorial fashion portrait using FLUX fp8 checkpoint. High-contrast lighting prompt engineered for maximum facial detail. 25 steps at CFG 3.5 with Euler sampler. Suitable for magazine-quality portrait generation. Use seed 42 as baseline, vary for different expressions.",
    category: "image", vram: "16GB", difficulty: "Intermediate",
    model: "flux1-dev-fp8.safetensors",
    modelPaths: [{ file: "flux1-dev-fp8.safetensors", dir: "ComfyUI/models/checkpoints/", downloadUrl: "https://huggingface.co/Comfy-Org/flux1-dev-fp8" }],
    customNodes: [], genTime: "~25s on RTX 5080", resolution: "1024×1024",
    tags: ["FLUX", "portrait", "editorial", "fashion", "16GB"],
    version: "v1.0",
    imageUrl: `/workflow-thumbs/30.webp`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "Fashion portrait of a woman with avant-garde makeup, high contrast editorial lighting, film grain",
    proTip: "FLUX excels at textures; don't over-prompt skin or it might become too smooth."
  },
  {
    id: "31", title: "ControlNet Canny — SDXL",
    description: "Canny edge detection guides SDXL generation. Strength 1.0 for maximum structural adherence.",
    longDescription: "Canny ControlNet extracts edge information from your input image and uses it to guide SDXL generation. Strength 1.0 locks the structure tightly to the input edges. Reduces to 0.7 for more creative freedom. Input any image, output a reimagined scene with the same composition.",
    category: "controlnet", vram: "10GB", difficulty: "Intermediate",
    model: "sd_xl_base_1.0.safetensors",
    modelPaths: [{ file: "controlnet-canny-sdxl-1.0.safetensors", dir: "ComfyUI/models/controlnet/", downloadUrl: "https://huggingface.co/diffusers/controlnet-canny-sdxl-1.0" }],
    customNodes: [], genTime: "~6s on RTX 5080", resolution: "1024×1024",
    tags: ["ControlNet", "Canny", "SDXL", "edge", "10GB"],
    version: "v1.0", featured: true,
    imageUrl: `/workflow-thumbs/31.png`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "A highly detailed glass sculpture of [input image subject], glowing with inner light",
    proTip: "Lower Canny strength to 0.6 if you want the model to have more creative freedom with the edges."
  },
  {
    id: "32", title: "ControlNet Depth — SDXL",
    description: "Depth map guides spatial composition. Strength 0.8 balances depth with creative freedom.",
    longDescription: "Depth ControlNet with Depth-Anything v2 for precise spatial composition control. Strength 0.8 preserves depth relationships while allowing texture/style variation. Load any image as depth input — the model generates a scene with matching foreground/background separation.",
    category: "controlnet", vram: "10GB", difficulty: "Intermediate",
    model: "sd_xl_base_1.0.safetensors",
    modelPaths: [{ file: "controlnet-depth-sdxl-1.0.safetensors", dir: "ComfyUI/models/controlnet/", downloadUrl: "https://huggingface.co/diffusers/controlnet-depth-sdxl-1.0" }],
    customNodes: [], genTime: "~6s on RTX 5080", resolution: "1024×1024",
    tags: ["ControlNet", "depth", "SDXL", "spatial", "10GB"],
    version: "v1.0",
    imageUrl: `/workflow-thumbs/32.webp`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "Input: depth map. Prompt: A majestic underwater coral kingdom, ethereal lighting",
    proTip: "Depth maps are superior to Canny for complex scenes; use Depth-Anything v2 for the best results."
  },
  {
    id: "33", title: "ControlNet OpenPose",
    description: "Pose-guided generation from skeleton input. Lock human poses precisely across generations.",
    longDescription: "OpenPose ControlNet reads body skeleton from input image and transfers the exact pose to generated characters. Strength 0.9 for tight pose adherence. Pre-loaded with superhero action pose prompt. Swap to any character prompt — the pose stays locked.",
    category: "controlnet", vram: "10GB", difficulty: "Intermediate",
    model: "sd_xl_base_1.0.safetensors",
    modelPaths: [{ file: "controlnet-openpose-sdxl-1.0.safetensors", dir: "ComfyUI/models/controlnet/", downloadUrl: "https://huggingface.co/thibaud/controlnet-openpose-sdxl-1.0" }],
    customNodes: [], genTime: "~5s on RTX 5080", resolution: "768×1024",
    tags: ["ControlNet", "OpenPose", "SD1.5", "pose", "10GB"],
    version: "v1.0",
    imageUrl: `/workflow-thumbs/33.webp`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "Input: pose of a jumping person. Prompt: A knight in golden armor leaping into battle",
    proTip: "Ensure your pose input is clear; overlapping limbs can sometimes confuse the pose estimator."
  },
  {
    id: "34", title: "ControlNet Lineart — Anime",
    description: "Anime lineart colorization. Line drawing input → fully colored anime illustration.",
    longDescription: "Lineart ControlNet with SD 1.5 anime model. Strength 1.0 locks to your linework precisely. Provide a clean black-on-white line drawing, prompt the colors and style, and get a fully rendered anime illustration. Works with both hand-drawn and digitally generated lines.",
    category: "controlnet", vram: "8GB", difficulty: "Intermediate",
    model: "dreamshaper_8.safetensors",
    modelPaths: [{ file: "controlnet-lineart-sd15.safetensors", dir: "ComfyUI/models/controlnet/", downloadUrl: "https://huggingface.co/lllyasviel/ControlNet-v1-1" }],
    customNodes: [], genTime: "~4s on RTX 5080", resolution: "512×512",
    tags: ["ControlNet", "lineart", "anime", "colorize", "8GB"],
    version: "v1.0",
    imageUrl: `/workflow-thumbs/34.webp`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "Input: character line art. Prompt: A futuristic girl with blue hair in school uniform, anime style",
    proTip: "Use a high CFG for colorization to ensure the AI follows the color cues in your prompt."
  },
  {
    id: "35", title: "ControlNet Tile Upscale",
    description: "ControlNet Tile for detail-preserving upscaling. Adds fine texture while respecting original.",
    longDescription: "Tile ControlNet upscale workflow. Input a lower-resolution image, get an AI-enhanced version with detailed textures added. Strength 0.7 adds enhancement without overriding the source. Combine with ESRGAN first for best results: ESRGAN 4x → Tile CN → Save.",
    category: "controlnet", vram: "10GB", difficulty: "Advanced",
    model: "sd_xl_base_1.0.safetensors",
    modelPaths: [{ file: "controlnet-tile-sdxl.safetensors", dir: "ComfyUI/models/controlnet/", downloadUrl: "https://huggingface.co/TTPlanet/TTPLanet_SDXL_Controlnet_Tile_Realistic" }],
    customNodes: [], genTime: "~6s on RTX 5080", resolution: "1024×1024",
    tags: ["ControlNet", "tile", "upscale", "detail", "10GB"],
    version: "v1.0",
    imageUrl: `/workflow-thumbs/35.webp`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "Input: 512px textured wall. Output: 2048px ultra-detailed realistic stone texture",
    proTip: "The tile model is perfect for textures; use it to upscale materials for 3D workflows."
  },
  {
    id: "36", title: "SDXL Batch ×4 Variations",
    description: "Generate 4 variations simultaneously. Concept art prompts pre-loaded. Same seed, 4 outputs.",
    longDescription: "Batch generation workflow with EmptyLatentImage set to batch_size=4. Generates 4 images in a single forward pass — 4x the output for similar compute time. Pre-loaded with concept art variation prompts. Each of the 4 images uses the same seed with batch index variation.",
    category: "specialty", vram: "12GB", difficulty: "Beginner",
    model: "sd_xl_base_1.0.safetensors",
    modelPaths: [{ file: "sd_xl_base_1.0.safetensors", dir: "ComfyUI/models/checkpoints/", downloadUrl: "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0" }],
    customNodes: [], genTime: "~12s on RTX 5080", resolution: "1024×1024",
    tags: ["batch", "SDXL", "variations", "concept", "12GB"],
    version: "v1.0", featured: true,
    imageUrl: `/workflow-thumbs/36.webp`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "Four different versions of a futuristic spaceship in deep space, sci-fi concept art",
    proTip: "Batching is the fastest way to explore variants of a single concept."
  },
  {
    id: "37", title: "SDXL Batch ×8 Grid",
    description: "8 simultaneous variations at 768×768. Product design and concept iteration at scale.",
    longDescription: "Maximum batch workflow at 8 images per run. Reduced to 768×768 to fit 8 latents in 12GB VRAM. Product design prompts pre-loaded for concept exploration. Run once, get 8 different interpretations to select from. Pair with image grid viewer for comparison.",
    category: "specialty", vram: "12GB", difficulty: "Intermediate",
    model: "sd_xl_base_1.0.safetensors",
    modelPaths: [{ file: "sd_xl_base_1.0.safetensors", dir: "ComfyUI/models/checkpoints/", downloadUrl: "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0" }],
    customNodes: [], genTime: "~20s on RTX 5080", resolution: "768×768",
    tags: ["batch", "SDXL", "8x", "concept", "12GB"],
    version: "v1.0",
    imageUrl: `/workflow-thumbs/37.webp`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "Eight iterations of a sleek designer chair for a modern living room, industrial design",
    proTip: "Use lowered resolution (768px) to fit 8 simultaneous images into memory."
  },
  {
    id: "38", title: "SDXL Logo & Brand Design",
    description: "Minimal vector-style logo generation. White background, professional brand identity.",
    longDescription: "Logo generation workflow with vector-style prompting. White background forces clean isolated outputs. Negative prompt eliminates photography and realism artifacts. CFG 7.5 with 25 steps for precise shape control. Generate 4+ variations and vectorize the best output in Illustrator.",
    category: "specialty", vram: "8GB", difficulty: "Beginner",
    model: "sd_xl_base_1.0.safetensors",
    modelPaths: [{ file: "sd_xl_base_1.0.safetensors", dir: "ComfyUI/models/checkpoints/", downloadUrl: "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0" }],
    customNodes: [], genTime: "~5s on RTX 5080", resolution: "1024×1024",
    tags: ["logo", "branding", "SDXL", "vector", "8GB"],
    version: "v1.0",
    imageUrl: `/workflow-thumbs/38.webp`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "A minimal vector logo of an eagle for a tech company, clean lines, white background, professional",
    proTip: "Add 'isolated on white background' with high negative weight for photography to keep logos clean."
  },
  {
    id: "39", title: "SDXL Concept Art Sheet",
    description: "Game character concept art with multiple view prompts. ArtStation quality preset.",
    longDescription: "Character design workflow for game and animation concept art. Artstation quality tags with multiple angle cues. 30 steps and CFG 7.5 for maximum detail. Generate 4 variations per run to get front/back/side/3/4 views. Export as reference sheet for 3D modelers.",
    category: "specialty", vram: "8GB", difficulty: "Intermediate",
    model: "sd_xl_base_1.0.safetensors",
    modelPaths: [{ file: "sd_xl_base_1.0.safetensors", dir: "ComfyUI/models/checkpoints/", downloadUrl: "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0" }],
    customNodes: [], genTime: "~6s on RTX 5080", resolution: "1024×1024",
    tags: ["concept art", "character", "game", "SDXL", "8GB"],
    version: "v1.0",
    imageUrl: `/workflow-thumbs/39.webp`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "Character sheet (front, back, side) of a futuristic ninja, sci-fi, detailed concept art",
    proTip: "Character sheets are best at 1024px; use the term 'orthographic view' for consistent results."
  },
  {
    id: "40", title: "FLUX Realistic Person",
    description: "Photorealistic human portraits with natural skin texture. DSLR-quality output.",
    longDescription: "Maximally realistic human generation using FLUX Dev. Natural skin texture prompts minimize plastic/AI-looking skin. DSLR cue adds photographic lens characteristics. 25 steps, Euler sampler with normal scheduler. The most convincing human generation currently possible in ComfyUI.",
    category: "image", vram: "16GB", difficulty: "Intermediate",
    model: "flux1-dev.safetensors",
    modelPaths: [{ file: "flux1-dev.safetensors", dir: "ComfyUI/models/unet/", downloadUrl: "https://huggingface.co/black-forest-labs/FLUX.1-dev" }],
    customNodes: [], genTime: "~22s on RTX 5080", resolution: "1024×1024",
    tags: ["FLUX", "realistic", "portrait", "DSLR", "16GB"],
    version: "v1.0",
    imageUrl: `/workflow-thumbs/40.webp`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "A realistic portrait of an elderly fisherman with a weathered face, sunset lighting, DSLR photography",
    proTip: "FLUX excels at realism; use natural lighting descriptions to avoid that AI plastic look."
  },
  {
    id: "41", title: "SDXL Interior Design",
    description: "Scandinavian interior design visualization. Natural light, architectural photography style.",
    longDescription: "Interior design workflow for rapid space visualization. Architectural photography prompts with natural lighting. Plants and minimalist style cues. 25 steps, CFG 7.0. Generate 4+ variations to explore different layouts and color palettes for design proposals.",
    category: "specialty", vram: "8GB", difficulty: "Beginner",
    model: "sd_xl_base_1.0.safetensors",
    modelPaths: [{ file: "sd_xl_base_1.0.safetensors", dir: "ComfyUI/models/checkpoints/", downloadUrl: "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0" }],
    customNodes: [], genTime: "~5s on RTX 5080", resolution: "1024×1024",
    tags: ["interior", "design", "Scandinavian", "SDXL", "8GB"],
    version: "v1.0",
    imageUrl: `/workflow-thumbs/41.webp`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "A minimalist Scandinavian living room with large windows, soft morning light, real photography",
    proTip: "Use keywords like 'soft organic light' to make the materials look more realistic."
  },
  {
    id: "42", title: "SD 1.5 Pixel Art Generator",
    description: "16-bit RPG sprite generation. Clean pixel art on transparent backgrounds for game assets.",
    longDescription: "Pixel art workflow using Deliberate v6 checkpoint. 16-bit game sprite prompts with game asset cues. Euler sampler at 20 steps for crisp pixel edges. 512×512 for native pixel art scale. Post-process: import to Aseprite, index to 16 colors, export as PNG sprite sheet.",
    category: "specialty", vram: "6GB", difficulty: "Beginner",
    model: "deliberate_v6.safetensors",
    modelPaths: [{ file: "deliberate_v6.safetensors", dir: "ComfyUI/models/checkpoints/", downloadUrl: "https://huggingface.co/XpucT/Deliberate" }],
    customNodes: [], genTime: "~2s on RTX 5080", resolution: "512×512",
    tags: ["pixel art", "game", "sprite", "SD1.5", "6GB"],
    version: "v1.0",
    imageUrl: `/workflow-thumbs/42.webp`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "A small RPG-style pixel-art hero sprite, 16-bit style, clean isolated background",
    proTip: "Avoid high CFG; it can break the clean pixel boundaries of your sprite."
  },
  {
    id: "43", title: "ACE Step 1.5 — Text to Song",
    description: "Full AI song generation with lyrics, melody, and instrumentation. Text prompt to complete audio track.",
    longDescription: "ACE Step 1.5 is a state-of-the-art music generation model running natively in ComfyUI. Describe a song in plain text — genre, mood, instrumentation, lyrical theme — and get a complete audio track with vocals and music. Uses TextEncodeAceStepAudio for full creative control over the composition. Supports song continuation and style transfer. Compatible with ComfyUI-AceStep custom node pack.",
    category: "specialty", vram: "16GB", difficulty: "Intermediate",
    model: "ace-step-v1.5.safetensors",
    modelPaths: [{ file: "ace-step-v1.5.safetensors", dir: "ComfyUI/models/ace_step/", downloadUrl: "https://huggingface.co/ACE-Step/ACE-Step-v1.5" }],
    customNodes: ["ComfyUI-AceStep"],
    genTime: "~45s on RTX 5080", resolution: "Audio / 30s clip",
    tags: ["audio", "music", "ace-step", "song", "16GB", "experimental"],
    version: "v1.5",
    imageUrl: `/workflow-thumbs/43.webp`,
    workflowJsonUrl: `/workflows/43.json`, altImages: [],
    proofPrompt: "An upbeat jazz-soul track with trumpet, piano, and brushed drums. Smooth vocalist, late night vibes, 90bpm. Key of F major.",
    proTip: "Be specific about BPM, key, and instrumentation in your prompt. ACE Step responds very well to music theory language."
  },
  {
    id: "44", title: "FLUX Food Photography",
    description: "Restaurant-quality food photography. Shallow DOF, warm lighting, appetizing styling.",
    longDescription: "Food photography workflow using FLUX Dev for maximum photorealism. Warm lighting and shallow depth of field prompts create magazine-quality food imagery. 20 steps at CFG 3.5. Useful for restaurant menus, recipe blogs, and food brand content creation.",
    category: "specialty", vram: "16GB", difficulty: "Beginner",
    model: "flux1-dev-fp8.safetensors",
    modelPaths: [{ file: "flux1-dev-fp8.safetensors", dir: "ComfyUI/models/checkpoints/", downloadUrl: "https://huggingface.co/Comfy-Org/flux1-dev-fp8" }],
    customNodes: [], genTime: "~22s on RTX 5080", resolution: "1024×1024",
    tags: ["food", "photography", "FLUX", "restaurant", "16GB"],
    version: "v1.0",
    imageUrl: `/workflow-thumbs/44.png`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "Product photography of a fresh gourmet burger on a wooden plate, studio lighting, macro",
    proTip: "Use 'bokeh' or 'shallow depth of field' to make the food pop from the background."
  },
  {
    id: "45", title: "SDXL Sci-Fi Environment",
    description: "Cinematic sci-fi interior scenes. Space station, holographic displays, crew. Movie quality.",
    longDescription: "Science fiction environment workflow for film, game, and book cover art. Holographic display and space station prompts create Star Trek/The Expanse atmosphere. 30 steps for maximum environmental detail. Use as background plates for compositing or standalone illustrations.",
    category: "specialty", vram: "8GB", difficulty: "Intermediate",
    model: "sd_xl_base_1.0.safetensors",
    modelPaths: [{ file: "sd_xl_base_1.0.safetensors", dir: "ComfyUI/models/checkpoints/", downloadUrl: "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0" }],
    customNodes: [], genTime: "~6s on RTX 5080", resolution: "1024×1024",
    tags: ["sci-fi", "environment", "SDXL", "cinematic", "8GB"],
    version: "v1.0",
    imageUrl: `/workflow-thumbs/45.webp`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "Inside a futuristic command deck on a spaceship, monitors glowing with data, hyper-realistic",
    proTip: "Focus on light sources; sci-fi is 80% about how well you handle neon and screen glow."
  },
  {
    id: "46", title: "SDXL Abstract Art Generator",
    description: "Flowing geometric abstract art. Gallery-quality output for prints and digital art.",
    longDescription: "Abstract art workflow with geometric and flow-field prompts. DPM++ 2M Karras at 25 steps delivers smooth color gradients and clean geometric forms. CFG 7.5 for strong artistic direction. Suitable for NFT generation, wall art prints, and digital illustration backgrounds.",
    category: "specialty", vram: "8GB", difficulty: "Intermediate",
    model: "sd_xl_base_1.0.safetensors",
    modelPaths: [{ file: "sd_xl_base_1.0.safetensors", dir: "ComfyUI/models/checkpoints/", downloadUrl: "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0" }],
    customNodes: [], genTime: "~6s on RTX 5080", resolution: "1024×1024",
    tags: ["abstract", "art", "geometric", "digital", "8GB"],
    version: "v1.0",
    imageUrl: `/workflow-thumbs/46.webp`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "Abstract liquid art with gold and black marble textures, floating geometry, artistic",
    proTip: "Abstract workflows are very sensitive to seed; try a batch of 4 to find the best composition."
  },
  {
    id: "47", title: "SDXL Surrealist Dreamscapes",
    description: "Salvador Dali-style surrealism. High symbolic detail, dreamlike compositions, smooth textures.",
    longDescription: "Surrealist workflow for fine art and concept illustration. High symbolism prompts with classic surrealist framing. 30 steps and CFG 8.0 for precise dream-logic adherence. Fluid surfaces and impossible geometry presets.",
    category: "specialty", vram: "8GB", difficulty: "Intermediate",
    model: "sd_xl_base_1.0.safetensors",
    modelPaths: [{ file: "sd_xl_base_1.0.safetensors", dir: "ComfyUI/models/checkpoints/", downloadUrl: "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0" }],
    customNodes: [], genTime: "~6s on RTX 5080", resolution: "1024×1024",
    tags: ["surrealism", "fine art", "SDXL", "dreamlike", "8GB"],
    version: "v1.0",
    imageUrl: `/workflow-thumbs/47.webp`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "A clock melting over a tree in a desert under a red sky, surrealism, high detail",
    proTip: "Use higher CFG (8.0+) to force the model to stick to your surrealist symbols precisely."
  },
  {
    id: "48", title: "SDXL Fantasy Creatures",
    description: "High-detail fantasy creature design. Dragons, griffins, and chimera concepts at 1024px.",
    longDescription: "Creature design workflow for game engines and fantasy illustration. Hyper-detailed scale, fur, and skin textures. 30 steps, CFG 7.5 for sharp anatomy. Pre-loaded with monster design prompts and cinematic studio lighting.",
    category: "specialty", vram: "8GB", difficulty: "Beginner",
    model: "sd_xl_base_1.0.safetensors",
    modelPaths: [{ file: "sd_xl_base_1.0.safetensors", dir: "ComfyUI/models/checkpoints/", downloadUrl: "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0" }],
    customNodes: [], genTime: "~6s on RTX 5080", resolution: "1024×1024",
    tags: ["fantasy", "creature", "monster", "SDXL", "8GB"],
    version: "v1.0",
    imageUrl: `/workflow-thumbs/48.png`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "A detailed fire dragon emerging from volcanic ash, orange glowing scales, epic fantasy art",
    proTip: "Keywords like 'anatomically correct' and 'sculpted' help build solid character forms."
  },
  {
    id: "49", title: "SDXL Cyberpunk City",
    description: "Bladerunner-style futuristic cities. Aerial night shots with neon glow and rain.",
    longDescription: "Urban environment workflow for cyberpunk and sci-fi world-building. Neon lighting, rain reflections, and high-altitude framing presets. CFG 7.5, 25 steps for sharp urban textures. Optimized for cinematic night environment plates.",
    category: "specialty", vram: "8GB", difficulty: "Beginner",
    model: "sd_xl_base_1.0.safetensors",
    modelPaths: [{ file: "sd_xl_base_1.0.safetensors", dir: "ComfyUI/models/checkpoints/", downloadUrl: "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0" }],
    customNodes: [], genTime: "~6s on RTX 5080", resolution: "1024×1024",
    tags: ["cyberpunk", "city", "neon", "environment", "8GB"],
    version: "v1.0",
    imageUrl: `/workflow-thumbs/49.png`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "A sprawling neon city at night, rain-slicked streets, flying cars, cyberpunk atmosphere",
    proTip: "Add 'night time' and 'neon glow' to your prompt to make the shadows deep and atmospheric."
  },
  {
    id: "50", title: "FLUX Cinematic Portrait v2",
    description: "Film grain analog portrait workflow. Side lighting, moody atmosphere, cinematic feel.",
    longDescription: "The most cinematic portrait workflow in the neuraldrift library. Film grain and analog photography prompts simulate a 35mm film aesthetic. Side lighting for dramatic moody shadows. FLUX Dev with separate loaders for maximum quality. Optimized for photorealistic character studies.",
    category: "image", vram: "16GB", difficulty: "Intermediate",
    model: "flux1-dev.safetensors",
    modelPaths: [{ file: "flux1-dev.safetensors", dir: "ComfyUI/models/unet/", downloadUrl: "https://huggingface.co/black-forest-labs/FLUX.1-dev" }],
    customNodes: [], genTime: "~22s on RTX 5080", resolution: "1024×1024",
    tags: ["FLUX", "cinematic", "film", "portrait", "16GB"],
    version: "v1.0", featured: true,
    imageUrl: `/workflow-thumbs/50.png`,
    workflowJsonUrl: null, altImages: [],
    proofPrompt: "Moody cinematic portrait of a mysterious man in a tuxedo, side lighting, film grain, analog photography",
    proTip: "Use 'reprographic' and 'kodachrome' to get a very specific analog film color palette."
  },
];


export function getWorkflowsByCategory(cat: WorkflowCategory) {
  return WORKFLOWS.filter((w) => w.category === cat);
}

export function getWorkflowsByVRAM(vram: VRAMTier) {
  const order: VRAMTier[] = ["6GB", "8GB", "10GB", "12GB", "16GB", "24GB"];
  const max = order.indexOf(vram);
  return WORKFLOWS.filter((w) => order.indexOf(w.vram) <= max);
}

export function getFeaturedWorkflows() {
  return WORKFLOWS.filter((w) => w.featured);
}

export function getWorkflow(id: string) {
  return WORKFLOWS.find((w) => w.id === id);
}
